name: plutoploy bot

on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  detect-and-inject:
    runs-on: ubuntu-latest
    if: github.actor != 'plutoploy[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Detect containerfile
        uses: plutoploy/auto-containerisation@main

      - name: Install buildah and podman
        run: |
          if ! command -v buildah &> /dev/null || ! command -v podman &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y buildah podman
          fi

      - name: Build image using Buildah
        id: build-image
        uses: redhat-actions/buildah-build@main
        with:
          image: ghcr.io/${{ github.repository }}
          tags: latest ${{ github.sha }} ${{ github.ref_name }}
          containerfiles: |
            ./Containerfile

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push to GHCR
        id: push
        uses: redhat-actions/push-to-registry@main
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@main
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
